"""
Manually compiled roster mapping NYC Council member names to district numbers.
Used as a fallback where Legistar's OfficeRecordExtraText is missing district info.

Caveats:
- Districts are given the last three council members elected to the position. Some names
may be repeated, missing, or inaccurate.
"""

import pandas as pd


def get_name_district():
    """Returns the manually curated name -> district_num roster as a DataFrame."""
    name_district = pd.DataFrame([
        # Manhattan
        {"person_name": "Christopher Marte",             "district_num": 1},
        {"person_name": "Margaret S. Chin",              "district_num": 1},
        {"person_name": "Alan J. Gerson",                "district_num": 1},
        {"person_name": "Virginia Maloney",              "district_num": 5},
        {"person_name": "Carlina Rivera",                "district_num": 2},
        {"person_name": "Harvey D. Epstein",             "district_num": 2},
        {"person_name": "Rosie Mendez",                  "district_num": 2},
        {"person_name": "Margarita Lopez",               "district_num": 2},
        {"person_name": "Erik D. Bottcher",              "district_num": 3},
        {"person_name": "Christine C. Quinn",            "district_num": 3},
        {"person_name": "Corey D. Johnson",              "district_num": 3},
        {"person_name": "Keith Powers",                  "district_num": 4},
        {"person_name": "Daniel R. Garodnick",           "district_num": 4},
        {"person_name": "Eva S. Moskowitz",              "district_num": 4},
        {"person_name": "Julie Menin",                   "district_num": 5},
        {"person_name": "Ben Kallos",                     "district_num": 5},
        {"person_name": "Jessica S. Lappin",             "district_num": 5},
        {"person_name": "Gifford Miller",                "district_num": 5},
        {"person_name": "Gale A. Brewer",                "district_num": 6},
        {"person_name": "Helen K. Rosenthal",            "district_num": 6},
        {"person_name": "Shaun Abreu",                   "district_num": 7},
        {"person_name": "Mark Levine",                   "district_num": 7},
        {"person_name": "Robert Jackson",                "district_num": 7},
        {"person_name": "Diana I. Ayala",                "district_num": 8},
        {"person_name": "Melissa Mark-Viverito",         "district_num": 8},
        {"person_name": "Kristin Richardson Jordan",     "district_num": 9},
        {"person_name": "Yusef Salaam",                  "district_num": 9},
        {"person_name": "Inez E. Dickens",               "district_num": 9},
        {"person_name": "Bill Perkins",                  "district_num": 9},
        {"person_name": "Philip Reed",                   "district_num": 9},
        {"person_name": "Carmen N. De La Rosa",          "district_num": 10},
        {"person_name": "Ydanis A. Rodriguez",           "district_num": 10},
        {"person_name": "Miguel Martinez",               "district_num": 10},
        {"person_name": "Eric Dinowitz",                 "district_num": 11},
        {"person_name": "Andrew D. Cohen",               "district_num": 11},
        {"person_name": "G. Oliver Koppell",             "district_num": 11},
        # Bronx
        {"person_name": "Kevin C. Riley",                "district_num": 12},
        {"person_name": "Andy L. King",                  "district_num": 12},
        {"person_name": "Andy King",                     "district_num": 12},
        {"person_name": "Larry B. Seabrook",             "district_num": 12},
        {"person_name": "Marjorie Velázquez",            "district_num": 13},
        {"person_name": "Kristy Marmorato",              "district_num": 13},
        {"person_name": "James Vacca",                   "district_num": 13},
        {"person_name": "Mark Gjonaj",                   "district_num": 13},
        {"person_name": "Madeline T. Provenzano",        "district_num": 13},
        {"person_name": "Pierina Ana Sanchez",           "district_num": 14},
        {"person_name": "Fernando Cabrera",              "district_num": 14},
        {"person_name": "Maria Baez",                    "district_num": 14},
        {"person_name": "Oswald J. Feliz",               "district_num": 15},
        {"person_name": "Ritchie J. Torres",             "district_num": 15},
        {"person_name": "Joel Rivera",                   "district_num": 15},
        {"person_name": "Althea V. Stevens",             "district_num": 16},
        {"person_name": "Vanessa L. Gibson",             "district_num": 16},
        {"person_name": "Helen D. Foster",               "district_num": 16},
        {"person_name": "Rafael Salamanca, Jr.",         "district_num": 17},
        {"person_name": "Maria Del Carmen Arroyo",       "district_num": 17},
        {"person_name": "Maria D. Arroyo",               "district_num": 17},
        {"person_name": "Amanda C. Farías",              "district_num": 18},
        {"person_name": "Ruben Diaz, Sr.",               "district_num": 18},
        {"person_name": "Darma V. Diaz",                 "district_num": 18},
        {"person_name": "Annabel Palma",                 "district_num": 18},
        # Queens
        {"person_name": "Vickie Paladino",               "district_num": 19},
        {"person_name": "Tony Avella",                   "district_num": 19},
        {"person_name": "Daniel J. Halloran III",        "district_num": 19},
        {"person_name": "Paul A. Vallone",               "district_num": 19},
        {"person_name": "Sandra Ung",                    "district_num": 20},
        {"person_name": "Peter A. Koo",                  "district_num": 20},
        {"person_name": "John C. Liu",                   "district_num": 20},
        {"person_name": "Francisco P. Moya",             "district_num": 21},
        {"person_name": "Julissa Ferreras-Copeland",     "district_num": 21},
        {"person_name": "Hiram Monserrate",              "district_num": 21},
        {"person_name": "Tiffany L. Cabán",              "district_num": 22},
        {"person_name": "Costa G. Constantinides",       "district_num": 22},
        {"person_name": "Peter F. Vallone, Jr.",         "district_num": 22},
        {"person_name": "Linda Lee",                     "district_num": 23},
        {"person_name": "Barry S. Grodenchik",           "district_num": 23},
        {"person_name": "Mark S. Weprin",                "district_num": 23},
        {"person_name": "David I. Weprin",               "district_num": 23},
        {"person_name": "James F. Gennaro",              "district_num": 24},
        {"person_name": "Rory I. Lancman",               "district_num": 24},
        {"person_name": "Shekar Krishnan",               "district_num": 25},
        {"person_name": "Daniel Dromm",                  "district_num": 25},
        {"person_name": "Helen Sears",                   "district_num": 25},
        {"person_name": "Julie Won",                     "district_num": 26},
        {"person_name": "James G. Van Bramer",           "district_num": 26},
        {"person_name": "Jimmy Van Bramer",              "district_num": 26},
        {"person_name": "Eric N. Gioia",                 "district_num": 26},
        {"person_name": "Nantasha M. Williams",          "district_num": 27},
        {"person_name": "I. Daneek Miller",              "district_num": 27},
        {"person_name": "Leroy G. Comrie, Jr.",          "district_num": 27},
        {"person_name": "Adrienne E. Adams",             "district_num": 28},
        {"person_name": "Allan W. Jennings, Jr.",        "district_num": 28},
        {"person_name": "Ruben Wills",                   "district_num": 28},
        {"person_name": "Lynn C. Schulman",              "district_num": 29},
        {"person_name": "Karen Koslowitz",               "district_num": 29},
        {"person_name": "Melinda R. Katz",               "district_num": 29},
        {"person_name": "Robert F. Holden",              "district_num": 30},
        {"person_name": "Elizabeth S. Crowley",          "district_num": 30},
        {"person_name": "Dennis P. Gallagher",           "district_num": 30},
        {"person_name": "Joann Ariola",                  "district_num": 32},
        {"person_name": "Eric A. Ulrich",                "district_num": 32},
        {"person_name": "Joseph P. Addabbo, Jr.",        "district_num": 32},
        # Brooklyn
        {"person_name": "Selvena N. Brooks-Powers",      "district_num": 31},
        {"person_name": "James Sanders, Jr.",            "district_num": 31},
        {"person_name": "Donovan J. Richards",           "district_num": 31},
        {"person_name": "Lincoln Restler",               "district_num": 33},
        {"person_name": "Stephen T. Levin",              "district_num": 33},
        {"person_name": "David Yassky",                  "district_num": 33},
        {"person_name": "Jennifer Gutiérrez",            "district_num": 34},
        {"person_name": "Antonio Reynoso",               "district_num": 34},
        {"person_name": "Diana Reyna",                   "district_num": 34},
        {"person_name": "Crystal Hudson",                "district_num": 35},
        {"person_name": "Laurie A. Cumbo",               "district_num": 35},
        {"person_name": "Letitia James",                 "district_num": 35},
        {"person_name": "James E. Davis",                "district_num": 35},
        {"person_name": "Chi A. Ossé",                   "district_num": 36},
        {"person_name": "Robert E. Cornegy, Jr.",        "district_num": 36},
        {"person_name": "Albert Vann",                   "district_num": 36},
        {"person_name": "Sandy Nurse",                   "district_num": 37},
        {"person_name": "Rafael L. Espinal, Jr.",        "district_num": 37},
        {"person_name": "Erik Martin Dilan",             "district_num": 37},
        {"person_name": "Alexa Avilés",                  "district_num": 38},
        {"person_name": "Carlos Menchaca",               "district_num": 38},
        {"person_name": "Sara M. Gonzalez",              "district_num": 38},
        {"person_name": "Shahana K. Hanif",              "district_num": 39},
        {"person_name": "Brad S. Lander",                "district_num": 39},
        {"person_name": "Bill De Blasio",                "district_num": 39},
        {"person_name": "Rita C. Joseph",                "district_num": 40},
        {"person_name": "Mathieu Eugene",                "district_num": 40},
        {"person_name": "Yvette D. Clarke",              "district_num": 40},
        {"person_name": "Darlene Mealy",                 "district_num": 41},
        {"person_name": "Tracy L. Boyland",              "district_num": 41},
        {"person_name": "Alicka Ampry-Samuel",           "district_num": 41},
        {"person_name": "Charles Barron",                "district_num": 42},
        {"person_name": "Inez D. Barron",                "district_num": 42},
        {"person_name": "Chris Banks",                   "district_num": 42},
        {"person_name": "Justin L. Brannan",             "district_num": 43},
        {"person_name": "Susan Zhuang",                  "district_num": 43},
        {"person_name": "Vincent J. Gentile",            "district_num": 43},
        {"person_name": "Kalman Yeger",                  "district_num": 44},
        {"person_name": "Simcha Felder",                 "district_num": 44},
        {"person_name": "David G. Greenfield",           "district_num": 44},
        {"person_name": "Farah N. Louis",                "district_num": 45},
        {"person_name": "Jumaane D. Williams",           "district_num": 45},
        {"person_name": "Kendall Stewart",               "district_num": 45},
        {"person_name": "Mercedes Narcisse",             "district_num": 46},
        {"person_name": "Alan N. Maisel",                "district_num": 46},
        {"person_name": "Lewis A. Fidler",               "district_num": 46},
        {"person_name": "Lew Fidler",                    "district_num": 46},
        {"person_name": "Ari Kagan",                     "district_num": 47},
        {"person_name": "Bridget G. Barclay",            "district_num": 47},
        {"person_name": "Mark Treyger",                  "district_num": 47},
        {"person_name": "Domenic M. Recchia, Jr.",       "district_num": 47},
        {"person_name": "Inna Vernikov",                 "district_num": 48},
        {"person_name": "Chaim M. Deutsch",              "district_num": 48},
        {"person_name": "Michael C. Nelson",             "district_num": 48},
        {"person_name": "Kamillah Hanks",                "district_num": 49},
        {"person_name": "Deborah L. Rose",               "district_num": 49},
        {"person_name": "Michael E. McMahon",            "district_num": 49},
        # Staten Island
        {"person_name": "David M. Carr",                 "district_num": 50},
        {"person_name": "Steven Matteo",                 "district_num": 50},
        {"person_name": "James S. Oddo",                 "district_num": 50},
        {"person_name": "Frank Morano",                  "district_num": 51},
        {"person_name": "Joseph C. Borelli",             "district_num": 51},
        {"person_name": "Vincent M. Ignizio",            "district_num": 51},
        {"person_name": "Vincent Ignizio",               "district_num": 51},
        {"person_name": "Andrew J. Lanza",               "district_num": 51},
        # Non-voting / non-district seats
        {"person_name": "Betsy Gotbaum",                 "district_num": None},
        {"person_name": "Letitia James",                 "district_num": None},  # as Public Advocate
        {"person_name": "Bill de Blasio",                "district_num": None},  # as Public Advocate
    ])

    name_district["person_name"] = name_district["person_name"].str.strip()
    name_district = name_district.drop_duplicates(subset="person_name", keep="first")

    return name_district